In [1]:
#a library is a collection of book or is a room where many book are stored tp be used later libaray is a collecion of precompiled code that can be used later on in a program for some specific well defined operation  phython libraries play a very vital role in field of machinelearning data science .data visulization

In [2]:
#2. numpy array are much faster and have strict requirement on the homogeneity of object#

In [6]:
import numpy as np

In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
np.shape(arr)

(3, 4)

In [10]:
np.ndim(arr)

2

In [11]:
np.size(arr)

12

In [15]:
arr[0]

array([1, 2, 3, 4])

In [17]:
arr[[2],[3]]

array([12])

In [19]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [22]:
np.random.randint(1,5 ,size=(3,3))

array([[1, 2, 4],
       [4, 3, 2],
       [3, 2, 3]])

In [23]:
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [24]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [28]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [29]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [32]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr1*arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [37]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
arr1@arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [40]:
arr1+arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [41]:
arr2-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
arr2/arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
#np.linalg. inv() function is used for inverse of matrix

In [44]:
#reshape

In [45]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
#broadcasting is used to add value in each element

In [47]:
arr+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])